name: e_commerce_app
description: "A E-Commerce App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#----------------------------------PACKAGES----------------------------------------#
dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Utility Packages
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.8


  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0






  #Product Specific


  #--------------------------------------------./ PACKAGES END -------------------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  #------------------------------------ LOCAL ASSETS ------------------------------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/onboarding_animation/
    - assets/auth_animations/
  
  #------------------------------------- LOCAL FONTS ---------------------------------------------#
  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


  
  
  
  
  
  
  
  
  
